baseURL = 'http://baimao01.vercel.app/'
languageCode = 'zh-cn'
title = 'Bai Mao'

theme = 'card'

[params]
    favicon = '/img/favicon.jpg'
    subtitle = '你见过会用电脑的猫吗？'
    [params.sidebar.avatar]
        enabled= 'true'
        local= 'true'
        src= 'img/avatar.jpg'

[[menu.main]]
name="首页"
url="/"
weight="1"
[[menu.main]]
name="归档"
url="/post"
weight="2"
[[menu.main]]
name="关于"
url="/about"
weight="3"